name: Continuous Integration
on: [push, pull_request]

jobs:
  build:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build --target test --tag todo-app:test .
      - run: docker run todo-app:test

  publish:
    name: Publish Docker image
    needs: build
    if: github.ref == 'refs/heads/module_9' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - run: echo Publishing!

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
